POST http://localhost:3003/api/blogs
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Imt6YW5iIiwiaWQiOiI2YTZmYmQxZDI2YTA4ZTVjOWRhMjhkZmQiLCJpYXQiOjE3ODU3OTQ0MjksImV4cCI6MTc4NTc5ODAyOX0.l0xRxxaYlZb4vv5NtSmgnemHEjsUGYUx3VKR1I62hJ8

{   
    "title": "Test user700",
    "author": "Test author700",
    "url": "https://www.testing.com",
    "likes": 2
}
